name: Deploy
on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Initialize GitHub deployment
    runs-on: ubuntu-latest
    permissions:
      deployments: write

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Deploy to staging
        if: github.event_name == 'push'
        uses: chrnorm/deployment-action@v2
        with:
          initial-status: success
          token: '${{ github.token }}'
          environment: staging
          environment-url: 'https://example.com'

      - name: Deploy to production
        if: github.event_name == 'check_run'
        uses: chrnorm/deployment-action@v2
        with:
          initial-status: success
          token: '${{ github.token }}'
          environment: production
          environment-url: 'https://example.com'
