name: Deploy
on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Initialize GitHub deployment
    runs-on: ubuntu-latest
    permissions:
      deployments: write

    steps:
      - uses: chrnorm/deployment-action@v2
        with:
          initial-status: success
          token: '${{ github.token }}'
          environment: 'staging'
          environment-url: 'https://example.com'
