name: Deploy
on:
  push:
    branches:
      - main

jobs:
  ohno:
    name: Oh no!
    runs-on: ubuntu-latest
    if: false

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          exit 1
          
      - name: Puke
        if: always() && !cancelled()
        run: echo "meh"
          
  anyway:
    name: Anyway
    needs: [ 'ohno' ]
    if: always() && !cancelled()
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          
  wtf:
    name: Wtf
    needs: [ 'anyway' ]
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
