name: Deploy
on:
  push:
    branches:
      - main

jobs:
  ohno:
    name: Oh no!
    runs-on: ubuntu-latest
    if: false

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          
  anyway:
    name: Anyway
    needs: [ 'ohno' ]
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
