name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      test:
        description: Test
        type: boolean
        required: true

jobs:
  ohno:
    name: Oh no!
    runs-on: ubuntu-latest
    if: true

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo "inputs.test: ${{ inputs.test }}"
          echo "inputs.test == null: ${{ inputs.test == null }}"
          echo "inputs.test == false: ${{ inputs.test == false }}"
          echo "inputs.test == true: ${{ inputs.test == true }}"
          echo "inputs.test == '': ${{ inputs.test == '' }}"
          echo "inputs.test != false: ${{ inputs.test != false }}"
          echo "inputs.test != 'false': ${{ inputs.test != 'false' }}"
          echo "inputs.test != '': ${{ inputs.test != '' }}"
          echo "false == 'false': ${{ false == 'false' }}"
          echo "true == 'true': ${{ true == 'true' }}"
          echo "true == 'false': ${{ true == 'false' }}"
          echo "true != 'false': ${{ true != 'false' }}"
          exit 1
          
      - name: Puke
        if: always() && !cancelled()
        run: echo "meh"
          
  anyway:
    name: Anyway
    needs: [ 'ohno' ]
    if: always() && !cancelled()
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          
  wtf:
    name: Wtf
    needs: [ 'anyway' ]
    if: always() && !cancelled() && needs.anyway.result != 'failed'
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
