name: Deploy
on:
  push:
    branches:
      - staging
  status:
    branches:
      - staging

jobs:
  deploy:
    name: Initialize GitHub deployment
    runs-on: ubuntu-latest
    permissions:
      deployments: write

    steps:
      - name: Deploy to staging
        if: github.event.type == 'push'
        uses: chrnorm/deployment-action@v2
        with:
          initial-status: success
          token: '${{ github.token }}'
          environment: staging
          environment-url: 'https://example.com'

      - name: Deploy to production
        if: github.event.type == 'status'
        uses: chrnorm/deployment-action@v2
        with:
          initial-status: success
          token: '${{ github.token }}'
          environment: production
          environment-url: 'https://example.com'
